### ISSUE TITLE
Missing null cache

### ISSUE THREAD

**Issue by juneb** [aws/aws-encryption-sdk-c#326]
The C SDK does not provide a null cache. 

The Encryption SDK in Java and Python provide a null cryptographic materials cache for testing, or to temporarily disable caching in your code. This is a safer alternative to other ways of disabling the cache, such as setting the cache capacity or security thresholds to 0.

**Comment by alex-chew** [comment]
Closing as subsumed by #562 due to spec change awslabs/aws-encryption-sdk-specification#166. The specification now requires that the local CMC support a capacity value of zero, so that it can act as a null cache. This is no less safe than a dedicated null cache, since the specification forbids the cache from storing more entries than its capacity value.
